server:
  port: 8899

mybatis:
  mapper-locations:
    - mapper/*
  type-aliases-package: com.bi.dbpedia.model
  config-location: classpath:mybatis-config.xml


spring:
  kafka:
    bootstrap-servers: hailuo.aliyun.com:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: dbpedia
      auto-commit-interval: 1000
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    druid:
      url: jdbc:mysql://cdb-ezjh4cma.bj.tencentcdb.com:10210/Business_Intelligence?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: abcd1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  data:
    neo4j:
      uri: bolt://192.168.3.14:7687
      username: neo4j
      password: abcd1234
  redis:
    host: lulu.aliyun.com
    database: 0
    port: 6379
    password: abcd12345
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms

redis:
  key:
    expire: 120 # 分钟

elasticsearch:
  ip: lulu.aliyun.com:9200